[package]
name = "cod"
version = "0.1.0"
edition = "2021"

[dependencies]
tree-sitter = "0.24.3"
tree-sitter-rust = "0.23.0"
streaming-iterator = "0.1.9"
tree-sitter-cpp = "0.23.1"

[build-dependencies]
cc="*"
